export type KuromojiPos =
    (typeof kuromojiPartOfSpeech)[keyof typeof kuromojiPartOfSpeech];

// Important POS that should be like higlighted or something.
export const importantPos: KuromojiPos[] = [
    'noun',
    'adjectival noun',
    'adjective',
    'adverb',
    'verb'
];

// Mapping from kuromoji to JMDict tags
export const kuromojiToJmdictTagsMapping = {
    noun: {
        'n-pref': 'noun, used as a prefix',
        'n-suf': 'noun, used as a suffix',
        n: 'noun (common) (futsuumeishi)',
        vs: 'noun or participle which takes the aux. verb suru',
        'n-t': 'noun (temporal) (jisoumeishi)',
        'n-adv': 'adverbial noun (fukushitekimeishi)',
        'adj-f': 'noun or verb acting prenominally',
        'adj-no': "nouns which may take the genitive case particle 'no'",
        'n-pr': 'proper noun',
        pn: 'pronoun'
    },
    'adjectival noun': {
        'adj-na': 'adjectival nouns or quasi-adjectives (keiyodoshi)',
        'adj-pn': 'pre-noun adjectival (rentaishi)'
    },
    adjective: {
        'adj-kari': "'kari' adjective (archaic)",
        'adj-shiku': "'shiku' adjective (archaic)",
        'adj-ix': 'adjective (keiyoushi) - yoi/ii class',
        'adj-nari': 'archaic/formal form of na-adjective',
        'adj-i': 'adjective (keiyoushi)',
        'adj-t': "'taru' adjective",
        'adj-ku': "'ku' adjective (archaic)"
    },
    adverb: {
        adv: 'adverb (fukushi)',
        'adv-to': "adverb taking the 'to' particle"
    },
    verb: {
        v5uru: 'Godan verb - Uru old class verb (old form of Eru)',
        'v2g-s': "Nidan verb (lower class) with 'gu' ending (archaic)",
        'v2g-k': "Nidan verb (upper class) with 'gu' ending (archaic)",
        'v5k-s': 'Godan verb - Iku/Yuku special class',
        'v2w-s':
            "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)",
        'v2n-s': "Nidan verb (lower class) with 'nu' ending (archaic)",
        'v5r-i': "Godan verb with 'ru' ending (irregular verb)",
        v1: 'Ichidan verb',
        'v2y-k': "Nidan verb (upper class) with 'yu' ending (archaic)",
        'v2a-s': "Nidan verb with 'u' ending (archaic)",
        'v5u-s': "Godan verb with 'u' ending (special class)",
        vi: 'intransitive verb',
        'v2y-s': "Nidan verb (lower class) with 'yu' ending (archaic)",
        vk: 'Kuru verb - special class',
        vn: 'irregular nu verb',
        vr: 'irregularq ru verb, plain form ends with -ri',
        vs: 'noun or participle which takes the aux. verb suru',
        vt: 'transitive verb',
        vz: 'Ichidan verb - zuru verb (alternative form of -jiru verbs)',
        'v2h-s': "Nidan verb (lower class) with 'hu/fu' ending (archaic)",
        proverb: 'proverb',
        'v2h-k': "Nidan verb (upper class) with 'hu/fu' ending (archaic)",
        'v2k-s': "Nidan verb (lower class) with 'ku' ending (archaic)",
        'v2s-s': "Nidan verb (lower class) with 'su' ending (archaic)",
        'v2k-k': "Nidan verb (upper class) with 'ku' ending (archaic)",
        v5aru: 'Godan verb - -aru special class',
        'v-unspec': 'verb unspecified',
        'v2r-k': "Nidan verb (upper class) with 'ru' ending (archaic)",
        'v2r-s': "Nidan verb (lower class) with 'ru' ending (archaic)",
        'v2b-k': "Nidan verb (upper class) with 'bu' ending (archaic)",
        'vs-s': 'suru verb - special class',
        'v2b-s': "Nidan verb (lower class) with 'bu' ending (archaic)",
        'vs-c': 'su verb - precursor to the modern suru',
        'vs-i': 'suru verb - included',
        'v2z-s': "Nidan verb (lower class) with 'zu' ending (archaic)",
        'v2m-s': "Nidan verb (lower class) with 'mu' ending (archaic)",
        'v1-s': 'Ichidan verb - kureru special class',
        'v2m-k': "Nidan verb (upper class) with 'mu' ending (archaic)",
        v4b: "Yodan verb with 'bu' ending (archaic)",
        v4g: "Yodan verb with 'gu' ending (archaic)",
        v4h: "Yodan verb with 'hu/fu' ending (archaic)",
        v4k: "Yodan verb with 'ku' ending (archaic)",
        v4m: "Yodan verb with 'mu' ending (archaic)",
        v4n: "Yodan verb with 'nu' ending (archaic)",
        v4s: "Yodan verb with 'su' ending (archaic)",
        v4r: "Yodan verb with 'ru' ending (archaic)",
        v4t: "Yodan verb with 'tsu' ending (archaic)",
        'v2t-k': "Nidan verb (upper class) with 'tsu' ending (archaic)",
        v5b: "Godan verb with 'bu' ending",
        'v2t-s': "Nidan verb (lower class) with 'tsu' ending (archaic)",
        v5g: "Godan verb with 'gu' ending",
        v5k: "Godan verb with 'ku' ending",
        v5n: "Godan verb with 'nu' ending",
        v5m: "Godan verb with 'mu' ending",
        'v2d-k': "Nidan verb (upper class) with 'dzu' ending (archaic)",
        v5r: "Godan verb with 'ru' ending",
        v5t: "Godan verb with 'tsu' ending",
        v5s: "Godan verb with 'su' ending",
        v5u: "Godan verb with 'u' ending",
        'v2d-s': "Nidan verb (lower class) with 'dzu' ending (archaic)"
    },
    auxiliary: {
        'aux-v': 'auxiliary verb',
        aux: 'auxiliary',
        'aux-adj': 'auxiliary adjective'
    },
    particle: {
        prt: 'particle'
    }
};

export const kuromojiPartOfSpeech = {
    その他: 'other',
    アルファベット: 'alphabet',
    サ変接続: 'sahen conjunction',
    ナイ形容詞語幹: 'nai adjective',
    フィラー: 'filler',
    一般: 'common',
    並立助詞: 'parallel marker',
    人名: 'person name',
    代名詞: 'pronoun',
    係助詞: 'particle',
    副助詞: 'adverbial particle',
    '副助詞／並立助詞／終助詞':
        'adverbial particle / parallel marker / sentence-ending particle',
    副詞: 'adverb',
    副詞化: 'adverbization',
    副詞可能: 'adverbizable',
    助動詞: 'auxiliary',
    助動詞語幹: 'auxiliary stem',
    助数詞: 'counter​',
    助詞: 'particle',
    助詞類接続: 'particle conjunction',
    動詞: 'verb',
    動詞接続: 'verb conjunction',
    動詞非自立的: 'verb non-independent',
    句点: 'period',
    名: 'name',
    名詞: 'noun',
    名詞接続: 'noun conjunction',
    固有名詞: 'proper noun',
    国: 'country',
    地域: 'area',
    姓: 'surname',
    引用: 'quote',
    形容動詞語幹: 'adjectival noun',
    形容詞: 'adjective',
    形容詞接続: 'adjective conjunction',
    感動詞: 'interjection',
    括弧閉: 'closed parentheses',
    括弧開: 'open parentheses',
    接尾: 'suffix',
    接続助詞: 'conjunction particle',
    接続詞: 'conjunction',
    接続詞的: 'conjunction',
    接頭詞: 'prefix',
    数: 'number',
    数接続: 'suffix to a number',
    格助詞: 'case-marking particle',
    特殊: 'irregular',
    空白: 'blank',
    終助詞: 'sentence-ending particle',
    組織: 'organization',
    縮約: 'contraction',
    自立: 'independent',
    記号: 'symbol',
    読点: 'comma',
    連体化: 'attributive form​',
    連体詞: 'adnominal adjective',
    連語: 'collocation',
    間投: 'interjectory',
    非自立: 'non independent'
} as const;

export const kuromojiConjugatedForms = {
    ガル接続: 'garu conjunction',
    仮定形: 'imaginary form',
    仮定縮約１: 'contraction',
    仮定縮約２: 'contraction',
    体言接続: 'word conjunction',
    体言接続特殊: 'irregular conjunction',
    体言接続特殊２: 'irregular conjunction',
    命令ｅ: 'imperative e',
    命令ｉ: 'imperative i',
    命令ｒｏ: 'imperative ro',
    命令ｙｏ: 'imperative yo',
    基本形: 'uninflected word',
    '基本形-促音便': 'uninflected word - double consonant euphonic change',
    文語基本形: 'kobun uninflected word',
    未然ウ接続: 'irrealis u conjunction',
    未然ヌ接続: 'irrealis nu conjunction',
    未然レル接続: 'irrealis reru conjunction',
    未然形: 'irrealis form',
    未然特殊: 'irrealis irregular',
    現代基本形: 'modern Japanese uninflected word',
    連用ゴザイ接続: 'continuative gozai conjunction',
    連用タ接続: 'continuative ta conjunction',
    連用テ接続: 'continuative te conjunction',
    連用デ接続: 'continuative de conjunction',
    連用ニ接続: 'continuative ni conjunction',
    連用形: 'continuative form',
    音便基本形: 'uninflected word'
} as const;

export const kuromojiConjugatedTypes = {
    'カ変・クル': 'kahen kuru',
    'カ変・来ル': 'kahen kuru',
    'サ変・−スル': 'sahen suru',
    'サ変・−ズル': 'sahen -zuru',
    'サ変・スル': 'sahen suru',
    ラ変: 'rahen',
    一段: 'ichidan',
    '一段・クレル': 'ichidan kureru',
    '一段・得ル': 'ichidan profit',
    '上二・ダ行': 'upper nidan da line',
    '下二・ガ行': 'lower nidan ga line',
    '下二・タ行': 'lower nidan ta line',
    '下二・ダ行': 'lower nidan da line',
    不変化型: 'invariant',
    '五段・カ行イ音便': 'godan ka line i euphonic change',
    '五段・カ行促音便': 'godan ka line double consonant euphonic change',
    '五段・カ行促音便ユク':
        'godan ka line double consonant euphonic change + yuku',
    '五段・ガ行': 'godan ga line',
    '五段・サ行': 'godan sa line',
    '五段・タ行': 'godan ta line',
    '五段・ナ行': 'godan na line',
    '五段・バ行': 'godan ba line',
    '五段・マ行': 'godan ma line',
    '五段・ラ行': 'godan ta line',
    '五段・ラ行アル': 'godan ra line + aru',
    '五段・ラ行特殊': 'godan ra line irregular',
    '五段・ワ行ウ音便': 'godan wa u euphonic change',
    '五段・ワ行促音便': 'godan wa line double consonant euphonic change',
    '四段・ハ行': 'yodan ha line',
    '形容詞・アウオ段': 'adjective auodan',
    '形容詞・イイ': 'ii adjective',
    '形容詞・イ段': 'adjective idan',
    '文語・キ': 'kobun ki',
    '文語・ケリ': 'kobun keri',
    '文語・ゴトシ': 'kobun gotoshi',
    '文語・ナリ': 'kobun nari',
    '文語・ベシ': 'kobun beshi',
    '文語・マジ': 'kobun mashi',
    '文語・リ': 'kobun li',
    '文語・ル': 'kobun ru',
    '特殊・ジャ': 'irregular ja',
    '特殊・タ': 'irregular ta',
    '特殊・タイ': 'irregular tai',
    '特殊・ダ': 'irregular da',
    '特殊・デス': 'irregular desu',
    '特殊・ナイ': 'irregular nai',
    '特殊・ヌ': 'irregular nu',
    '特殊・マス': 'irregular masu',
    '特殊・ヤ': 'irregular ya'
} as const;
